name: Build macOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install pyinstaller
      - name: Build macOS App
        run: pyinstaller --onefile --windowed --name "MyApp" main.py
      - name: Debug: List dist contents
        run: ls -R dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp
          path: dist/
