name: Build macOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install pyinstaller
      - name: Build macOS App
        run: pyinstaller --onefile main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyApp
          path: dist/MyApp.app
