name: Build macOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read
      actions: read
    steps:
    
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install pyinstaller
      - name: Build macOS App
        run: pyinstaller --onefile main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp
          path: dist/MyApp.app
